a = input('Digite Algo: ')
print('O tipo primitivo desse valor é', type(a))
print('Ele é alfanúmerico? ', a.isalnum())
print('Ele é númerico? ', a.isnumeric())
print('Ele é alfabético? ', a.isalpha())
print('Ele está em letras minúsculas? ', a.islower())
print('Ele está em letras maiúsculas? ', a.isupper())
print('Ele é imprimível? ', a.isprintable())
print('Ele é um espaço? ', a.isspace())
print('Ele é um dígito? ', a.isdigit())
print('Está capitalizada? ', a.istitle())
print('Fim do teste')